language: python
python:
    - 3.6.2

services:
    - docker
    - docker-compose
  
install:
    - docker build .

script:
    - docker-compose run web python init_db.py
    - docker-compose run --rm web python -m unittest