version: '3.3'

services:

  db:
    image: postgres:latest
    networks:
     - backend
    restart:
      always
    volumes:
      - ./docker_volumes/postgresql/data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      PORT: 3000
    networks:
     - backend
    restart:
      always
    ports:
      - "3000:3000"
    command: bash -c "python init_db.py && python main.py" 

networks:
  backend: